name: movers
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  otp_text_field: ^1.1.3
  carousel_slider: ^5.1.1
  image_picker: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shimmer: ^3.0.0
  google_places_flutter: ^2.0.6
  fluttertoast: ^8.2.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.14
  flutter_launcher_icons: ^0.13.1
  flutter_html: ^3.0.0-beta.2
  share_plus: ^12.0.1
  provider: ^6.0.5
  onesignal_flutter: ^5.0.4
  webview_flutter: ^4.1.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.2.0-beta-1
  geocoding: ^2.1.0
  razorpay_flutter: ^1.3.5
  flutter_spinkit: ^5.2.1
  http_auth: ^1.0.4
  flutter_sslcommerz: ^2.3.9
  flutter_bkash: ^0.2.0
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^11.0.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpeg"
  min_sdk_android: 21
 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: urbani_extrabold
      fonts:
        - asset: assets/fonts/urbani_extrabold.ttf

    - family: urbani_regular
      fonts:
        - asset: assets/fonts/urbani_regular.ttf
